# Generated by Django 4.1.5 on 2023-01-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
